# Generated by Django 5.2.7 on 2026-02-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bloodGroup',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_guest',
        ),
        migrations.RemoveField(
            model_name='user',
            name='t_shirt_size',
        ),
        migrations.AlterField(
            model_name='user',
            name='add_my_image_to_magazine',
            field=models.BooleanField(default=False),
        ),
    ]
