# Generated by Django 5.2.7 on 2026-02-25 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='gift_received',
        ),
    ]
