# Generated by Django 5.2.7 on 2026-02-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_gift_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_image_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL of the generated ticket image', max_length=500, null=True),
        ),
    ]
