# Generated by Django 5.2.7 on 2026-02-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_ticket_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_image_url',
        ),
    ]
